In [ ]:
# Setup Cell: Run this to pull the workshop data files into Colab
import os

if os.path.exists('ccv-bootcamp-python-2026'):
  !rm -rf /content/ccv-bootcamp-python-2026
!git clone --quiet https://github.com/brown-ccv/ccv-bootcamp-python-2026.git
print("✅ Workshop data successfully loaded!")

# Intro to Python Programming II: Packages, Environments, Tabular Data

Most of this lecture will be presented through slides. This notebook will be used interactively for you to try out examples and perform exercises.

---

## How to use the notebook
1.   There are code cells and text cells.
2.   Execute code cells by pressing the play button ▶️ at the top left of the cell or `shift` + `enter`
3.   Cells can be run in any order, but it is best practice to execute from top to bottom.
4.   To start, run the setup code cell below to pull the workshop data files into Colab.

In [1]:
import pandas as pd

In [2]:
df_data = pd.read_csv('../data/processed/combined_file.csv')

In [3]:
df_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 33850 entries, 0 to 33849
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   State Code                  33850 non-null  int64
 1   County Code                 33850 non-null  int64
 2   Site Number                 33850 non-null  int64
 3   Parameter Code              33850 non-null  int64
 4   POC                         33850 non-null  int64
 5   Latitude                    33850 non-null  float64
 6   Longitude                   33850 non-null  float64
 7   Datum                       33850 non-null  str
 8   Parameter Name              33850 non-null  str
 9   Duration Description        33850 non-null  str
 10  Pollutant Standard          3279 non-null   str
 11  Date (Local)                33850 non-null  str
 12  Year                        33850 non-null  int64
 13  Day In Year (Local)         33850 non-null  int64
 14  Units of Measure            33850 non-null  str
 15  Exceptional Data Type       0 non-null      float64
 16  Nonreg Observation Count    0 non-null      float64
 17  Observation Count           33850 non-null  int64
 18  Observation Percent         33850 non-null  float64
 19  Nonreg Arithmetic Mean      0 non-null      float64
 20  Arithmetic Mean             33850 non-null  float64
 21  Nonreg First Maximum Value  0 non-null      float64
 22  First Maximum Value         33850 non-null  float64
 23  First Maximum Hour          33850 non-null  int64
 24  AQI                         33850 non-null  str
 25  Daily Criteria Indicator    33850 non-null  str
 26  Tribe Name                  0 non-null      float64
 27  State Name                  33850 non-null  str
 28  County Name                 33850 non-null  str
 29  City Name                   33850 non-null  str
 30  Local Site Name             33850 non-null  str
 31  Address                     33850 non-null  str
 32  MSA or CBSA Name            33850 non-null  str
 33  Data Source                 33850 non-null  str
dtypes: float64(10), int64(9), str(15)
memory usage: 8.8 MB

In [15]:
df_data.head(20)

,State Code,County Code,Site Number,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Duration Description,...,AQI,Daily Criteria Indicator,Tribe Name,State Name,County Name,City Name,Local Site Name,Address,MSA or CBSA Name,Data Source
0,44,7,22,88101,3,41.807469,-71.412968,NAD83,PM2.5 - Local Conditions,1 HOUR,...,.,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
1,44,7,22,88101,3,41.807469,-71.412968,NAD83,PM2.5 - Local Conditions,24-HR BLK AVG,...,39,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
2,44,7,22,88101,3,41.807469,-71.412968,NAD83,PM2.5 - Local Conditions,24-HR BLK AVG,...,39,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
3,44,7,22,61104,1,41.807469,-71.412968,NAD83,Wind Direction - Resultant,1 HOUR,...,.,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
4,44,7,22,84313,1,41.807469,-71.412968,NAD83,Black carbon PM2.5 STP,1 HOUR,...,.,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
5,44,7,22,61107,1,41.807469,-71.412968,NAD83,Std Dev Vt Wind Direction,1 HOUR,...,.,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
6,44,7,22,87101,1,41.807469,-71.412968,NAD83,"Particle Number, Total Count",1 HOUR,...,.,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
7,44,7,22,62201,1,41.807469,-71.412968,NAD83,Relative Humidity,1 HOUR,...,.,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
8,44,7,22,62101,1,41.807469,-71.412968,NAD83,Outdoor Temperature,1 HOUR,...,.,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
9,44,7,22,88101,3,41.807469,-71.412968,NAD83,PM2.5 - Local Conditions,1 HOUR,...,.,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
10,44,7,22,88101,3,41.807469,-71.412968,NAD83,PM2.5 - Local Conditions,24-HR BLK AVG,...,17,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
11,44,7,22,88101,3,41.807469,-71.412968,NAD83,PM2.5 - Local Conditions,24-HR BLK AVG,...,17,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
12,44,7,22,61104,1,41.807469,-71.412968,NAD83,Wind Direction - Resultant,1 HOUR,...,.,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
13,44,7,22,84313,1,41.807469,-71.412968,NAD83,Black carbon PM2.5 STP,1 HOUR,...,.,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
14,44,7,22,61107,1,41.807469,-71.412968,NAD83,Std Dev Vt Wind Direction,1 HOUR,...,.,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
15,44,7,22,87101,1,41.807469,-71.412968,NAD83,"Particle Number, Total Count",1 HOUR,...,.,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
16,44,7,22,62201,1,41.807469,-71.412968,NAD83,Relative Humidity,1 HOUR,...,.,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
17,44,7,22,62101,1,41.807469,-71.412968,NAD83,Outdoor Temperature,1 HOUR,...,.,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
18,44,7,22,88101,3,41.807469,-71.412968,NAD83,PM2.5 - Local Conditions,1 HOUR,...,.,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
19,44,7,22,88101,3,41.807469,-71.412968,NAD83,PM2.5 - Local Conditions,24-HR BLK AVG,...,19,Y,NaN,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart

In [11]:
df_data[['State Name', 'County Name', 'City Name', 'Local Site Name', 'Address',
       'MSA or CBSA Name', 'Data Source']]

,State Name,County Name,City Name,Local Site Name,Address,MSA or CBSA Name,Data Source
0,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
1,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
2,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
3,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
4,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
...,...,...,...,...,...,...,...
33845,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
33846,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
33847,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
33848,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart
33849,Rhode Island,Providence,Providence,CCRI Liston Campus ROOFTOP,"1 Hilton St, PROVIDENCE RI","Providence-Warwick, RI-MA",AQS Data Mart

In [16]:
df_data['Parameter Name'].unique()

<StringArray>
[        'PM2.5 - Local Conditions',       'Wind Direction - Resultant',
           'Black carbon PM2.5 STP',        'Std Dev Vt Wind Direction',
     'Particle Number, Total Count',                'Relative Humidity',
              'Outdoor Temperature',           'Wind Speed - Resultant',
                'Chromium PM10 STP',                    'Lead PM10 STP',
            'PM10 Total 0-10um STP',           '1,3,5-Trimethylbenzene',
           '1,2,4-Trimethylbenzene',                          'Styrene',
                       'm/p Xylene',                          'Benzene',
                          'Toluene',                         'o-Xylene',
                      'Cyclohexane',           '2,2,4-Trimethylpentane',
                     'Formaldehyde',                     'Acetaldehyde',
                        'n-Pentane',                         'n-Hexane',
                        'n-Heptane',                         'n-Octane',
               'Ethylene dibromide',                    'Chlorobenzene',
        '1,1,2,2-Tetrachloroethane',                         'n-Butane',
              'Ethylene dichloride',              '1,2-Dichloropropane',
          'cis-1,3-Dichloropropene',        'trans-1,3-Dichloropropene',
                   'Vinyl chloride',                    'Acrylonitrile',
             '1,1-Dichloroethylene',               '1,1-Dichloroethane',
                       'Chloroform',                'Trichloroethylene',
              'Tetrachloroethylene',              '1,4-Dichlorobenzene',
             'Carbon tetrachloride',                    'alpha.-Pinene',
                   'Ethylene oxide',                  'Dichloromethane',
                    '1,3-Butadiene',          'Methyl tert-butyl ether',
           '1,2,4-Trichlorobenzene',                      'Naphthalene',
                        'Bromoform',            '1,1,2-Trichloroethane',
       'trans-1,2-Dichloroethylene',        '1,1,1,2-Tetrachloroethane',
              '1,3-Dichlorobenzene',              '1,2-Dichlorobenzene',
                     'Chloroethane',           'Trichlorofluoromethane',
              'Methyl ethyl ketone',                'Methyl chloroform',
              'Acrolein - Verified',                    'Chloromethane',
                 'Cadmium PM10 STP',               'Manganese PM10 STP',
                  'Nickel PM10 STP',                 'Arsenic PM10 STP',
                     'Ethylbenzene',               'Beryllium PM10 STP',
                          'Acetone', 'Indeno[1,2,3-cd]pyrene (TSP) STP',
   'Benzo[k]fluoranthene (TSP) STP',         'Benzo[e]pyrene (TSP) STP',
 'Dibenzo[a,h]anthracene (TSP) STP',   'Benzo[g,h,i]perylene (TSP) STP',
         'Benzo[a]pyrene (TSP) STP',                 'Pyrene (TSP) STP',
               'Coronene (TSP) STP',               'Perylene (TSP) STP',
     'Benzo[a]anthracene (TSP) STP',   'Benzo[b]fluoranthene (TSP) STP',
         'Acenaphthylene (TSP) STP',               'Fluorene (TSP) STP',
           'Phenanthrene (TSP) STP',             'Anthracene (TSP) STP',
           'Fluoranthene (TSP) STP',                     'Benzaldehyde',
                'Antimony PM10 STP',            'Naphthalene (TSP) STP',
           'Acenaphthene (TSP) STP',                     'Bromomethane',
                    'Butyl benzene',               'Chrysene (TSP) STP']
Length: 92, dtype: str

In [20]:
df_data.nunique()

State Code                       1
County Code                      1
Site Number                      1
Parameter Code                  92
POC                              6
Latitude                         1
Longitude                        1
Datum                            1
Parameter Name                  92
Duration Description             3
Pollutant Standard               3
Date (Local)                  1502
Year                             5
Day In Year (Local)            366
Units of Measure                 9
Exceptional Data Type            0
Nonreg Observation Count         0
Observation Count               19
Observation Percent             18
Nonreg Arithmetic Mean           0
Arithmetic Mean               6883
Nonreg First Maximum Value       0
First Maximum Value           2371
First Maximum Hour              24
AQI                             83
Daily Criteria Indicator         2
Tribe Name                       0
State Name                       1
County Name                      1
City Name                        1
Local Site Name                  1
Address                          1
MSA or CBSA Name                 1
Data Source                      1
dtype: int64

In [21]:
df_data.describe()

,State Code,County Code,Site Number,Parameter Code,POC,Latitude,Longitude,Year,Day In Year (Local),Exceptional Data Type,Nonreg Observation Count,Observation Count,Observation Percent,Nonreg Arithmetic Mean,Arithmetic Mean,Nonreg First Maximum Value,First Maximum Value,First Maximum Hour,Tribe Name
count,33850.0,33850.0,33850.0,33850.000000,33850.000000,3.385000e+04,33850.000000,33850.000000,33850.000000,0.0,0.0,33850.000000,33850.000000,0.0,33850.000000,0.0,33850.000000,33850.000000,0.0
mean,44.0,7.0,22.0,55757.373589,2.422718,4.180747e+01,-71.412968,2023.497134,178.539764,NaN,NaN,8.250251,99.858316,NaN,96.034701,NaN,185.384981,3.471462,NaN
std,0.0,0.0,0.0,21865.302910,1.667990,7.105532e-15,0.000000,1.130711,106.463960,NaN,NaN,10.664812,2.400088,NaN,854.898806,NaN,1789.719518,6.435808,NaN
min,44.0,7.0,22.0,17141.000000,1.000000,4.180747e+01,-71.412968,2022.000000,1.000000,NaN,NaN,1.000000,25.000000,NaN,-1.375000,NaN,-1.300000,0.000000,NaN
25%,44.0,7.0,22.0,43801.000000,1.000000,4.180747e+01,-71.412968,2022.000000,85.000000,NaN,NaN,1.000000,100.000000,NaN,0.032000,NaN,0.032000,0.000000,NaN
50%,44.0,7.0,22.0,45810.000000,2.000000,4.180747e+01,-71.412968,2023.000000,178.000000,NaN,NaN,1.000000,100.000000,NaN,0.671500,NaN,0.800000,0.000000,NaN
75%,44.0,7.0,22.0,82102.000000,3.000000,4.180747e+01,-71.412968,2024.000000,271.000000,NaN,NaN,24.000000,100.000000,NaN,6.800000,NaN,9.000000,4.000000,NaN
max,44.0,7.0,22.0,88101.000000,7.000000,4.180747e+01,-71.412968,2026.000000,366.000000,NaN,NaN,24.000000,100.000000,NaN,32061.416667,NaN,55558.000000,23.000000,NaN

Questions
1. What is the structure of the data?
2. What are the data types of the columns?
3.
4. Do we need all the columns?
6 How many unique values are there in each column?
5. Do we need all the rows?